[Log]
Output = "stream"

[Server]
PortNumber = 8080

[DB]
UserID     = "root"
Password   = "root"
HostName   = "127.0.0.1"
PortNumber = "3306"
Name       = "apprank"

[Watch]
Interval   = 60
MaxCount   = 200
